### ISSUE TITLE
棋盘不能随窗口大小变化而缩放

### ISSUE THREAD

**Issue by KangLin** [XMuli/ChineseChess#1]

**Comment by XMuli** [comment]
It was written as a permalink before, but I'm a little busy right now, so you're welcome to submit a pr (if you're interested).

**Comment by Bruce-Ch** [comment]
我计划对此作出修改，已经完成了ui的重新设计，正在准备重写paintEvent

**Comment by KangLin** [comment]
UI建议使用中国象棋控件：https://github.com/KangLin/ChineseChessControl

**Comment by XMuli** [comment]
@Bruce-Ch 很棒， 已经合并你的贡献，表示感谢； 修复参见 #2
