### ISSUE TITLE
棋子实现方式建议

### ISSUE THREAD

**Issue by Ubuntuser2012** [XMuli/ChineseChess#10]
你好，棋子可以考虑使用graphicsitem实现，操作性会提升很多😊

**Comment by XMuli** [comment]
我擦， 昨天就回复了此消息，但是没有点击确定， 好几次都回复失败了，（误点击快进，再切换回来就丢失了内容）。

这是之前为了学习 Qt 的基础知识的时候，为了尽可能的使用多的底层的知识和学习，所以选择使用画笔和画刷等来绘画。对于 改用 graphicsitem 可能也是一个比较好的方式， 有兴趣可以试试。   非常感谢你的 cmake 的提交，之前就想写一份 cmake 的（但是不是很熟悉）。

PS： 看你的头像，我可能在某个群里见过，眼熟~  （开心， 😊， 逃，，，）

**Comment by Ubuntuser2012** [comment]
😂😂好的，最近有点累
