### ISSUE TITLE
高分辨率下界面显示问题

### ISSUE THREAD

**Issue by lilucpp** [XMuli/ChineseChess#12]
高分辨率下的界面显示如下图。建议在>=5.6的qt上开启高dpi适配。
```c++
int main(int argc, char *argv[])
{
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
    QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QGuiApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);
#endif
    //....
}
```
![chooseGUI](https://user-images.githubusercontent.com/17497629/129292885-5e10155c-357d-4c69-bc60-37053f4079fb.png)
![ChessBoard](https://user-images.githubusercontent.com/17497629/129292890-da265084-50b8-4282-93fa-15c65d9a81b7.png)

**Comment by XMuli** [comment]
额， 光写这几行有点不行，比如字体大小当初写死了；后面有空再来改写吧

**Comment by yjmthu** [comment]
用Qt6编译后没有这个问题, 但是ai却有新的问题

**Comment by XMuli** [comment]
> 用Qt6编译后没有这个问题, 但是ai却有新的问题

只要屏幕分辨率 大于 1920 * 1080 均不会出现此问题（如 1080 && 100%缩放、3K && 200% 缩放， 4K && 150% 缩放），或者缩放过大。

**Comment by yjmthu** [comment]
我下载那个release版本的就和上面一样有分辨率问题

**Comment by XMuli** [comment]
@yjmthu 看看新的代码编译版本是否会这样（下载那 release 版本很久没更新了，后续加了较多新功能，但没时间打包）？另外你的环境分辨率和缩放比是？

**Comment by yjmthu** [comment]
2560x1600, 200%.
目前用QT6, 所以即使不用setAttribute调也不会存在分辨率的问题了.

**Comment by XMuli** [comment]
**更新：2022.01.01**

昂~；先Mark 下； 目前最新版本都已经更到 [https://github.com/xmuli/chinessChess/releases/tag/v6.0](https://github.com/xmuli/chinessChess/releases/tag/v6.0) ；

顺便，新年快乐鸭~~ ✨✨
