### ISSUE TITLE
对将的情况并没有考虑进去

### ISSUE THREAD

**Issue by kira-yamatoo** [XMuli/ChineseChess#13]
ChessBoard类的：bool canMoveJIANG(int moveId, int killId, int row, int col)函数需要考虑对将的情况
```
bool ChessBoard::canMoveJIANG(int moveId, int killId, int row, int col)
{
    //对将的情况
    if (killId != -1 && m_ChessPieces[killId].m_emType == m_ChessPieces->JIANG)
        return canMoveCHE(moveId, killId, row, col );
    //请加上这一段

    if(m_ChessPieces[moveId].m_bRed) //红 将
    {
        if(row < 7 || col < 3 || col > 5)
            return false;
    }
    else  //黑 将
    {
        if(row > 2 || col < 3 || col > 5)
            return false;
    }

    int dr = m_ChessPieces[moveId].m_nRow - row;
    int dc = m_ChessPieces[moveId].m_nCol - col;
    int d = abs(dr)*10 + abs(dc);
   
    if(d== 1 || d == 10)
        return true;

    return false;
}
```

**Comment by XMuli** [comment]
你发现了一块没想到的地方，大佬可以直接来个 PR 的形式提交
![QQ图片20210906231224](https://user-images.githubusercontent.com/33887845/132237408-46e35623-a85d-4e1b-8d8c-0b39abcafc39.gif)

**Comment by kira-yamatoo** [comment]
> 你发现了一块没想到的地方，大佬可以直接来个 PR 的形式提交
> ![QQ图片20210906231224](https://user-images.githubusercontent.com/33887845/132237408-46e35623-a85d-4e1b-8d8c-0b39abcafc39.gif)

啊这 /doge我还没试过pull request

**Comment by XMuli** [comment]
这个就可以是你练手的地方，合并添加成功还有小绿格子🤪

**Comment by kira-yamatoo** [comment]
> 这个就可以是你练手的地方，合并添加成功还有小绿格子🤪

好耶 (๑•̀ㅂ•́)و✧

**Comment by kira-yamatoo** [comment]
> 这个就可以是你练手的地方，合并添加成功还有小绿格子🤪

可以看一下PR吗 提交了

**Comment by XMuli** [comment]
嗯嗯， 已回复

**Comment by XMuli** [comment]
如果在 commit 里面写上， `#14` 时候，当 PR 被合并时候，是 bot 会自动关闭 此 Issues 的；

**Comment by XMuli** [comment]
”对将“ 情况已修复，如有兴趣，可参见 https://github.com/xmuli/chinessChess/commit/4eb2cb9f0c01c463a906932f0e7f21c42ce0128d 实现

![image](https://user-images.githubusercontent.com/33887845/132944471-fc02dea8-25cb-439b-aed2-3e162e7077e8.png)
