### ISSUE TITLE
ChessBoard::hongMenFeast() 问题

### ISSUE THREAD

**Issue by kira-yamatoo** [XMuli/ChineseChess#16]
![QQ图片20210911184528](https://user-images.githubusercontent.com/57071998/132945358-46707894-4395-4766-9cc9-676882f2845e.png)

**Comment by kira-yamatoo** [comment]
可以吧这个函数改成将军 即其中一方落子结束 换边后执行该函数 获取上一回合所属方所有棋子的移动是否可以直接移动至将军处 提醒本回合的玩家优先解围 否则下回合判输

**Comment by kira-yamatoo** [comment]
> 可以吧这个函数改成将军 即其中一方落子结束 换边后执行该函数 获取上一回合所属方所有棋子的移动是否可以直接移动至将军处 提醒本回合的玩家优先解围 否则下回合判输

需要判断所有棋子移动时 传参killId的id为对方将军的棋子id即可

**Comment by XMuli** [comment]
我丢， 判断了有纰漏； 我抓个虫；

> 可以吧这个函数改成将军

确实这样比较好，还没到胜负已分的局面； 我改改

**Comment by XMuli** [comment]
已修复，目前只针对 1 式给出了提示
**“将军”** 有两层含义
1. 自己错下，让对方有机会直接击杀本方（但可选不这样执子；但仍提醒可直接取胜）
2. 对方下棋（非对将），照成的将军（这种提示就略复杂一点，需要单独遍历对方所有还存活棋子，可一击必杀自己的可能棋子，然后给出提示）

且此处也可有一个音效提示， mark 下
https://github.com/xmuli/chinessChess/blob/fc108e9e4ff35b2343ddaced76a28be6f37cd424/ChessBoard.cpp#L367-L370


![image](https://user-images.githubusercontent.com/33887845/132947824-d2752ca4-d4a1-42ca-b63e-6f8300254e53.png)
