### ISSUE TITLE
添加 Linux ARM 构建

### ISSUE THREAD

**Issue by hmsjy2017** [XMuli/ChineseChess#21]
chineseChess 不支持 armhf/arm64，有点可惜，树莓派等 arm 设备无法使用，望支持。

**Comment by XMuli** [comment]
啊，这！，同源异构这不是我所擅长的； 可能需要后面某位邂逅有此技的大佬帮助。

<img src="https://user-images.githubusercontent.com/33887845/135724411-a0c33e63-05e8-4efd-a189-cdb8eb506ec7.jpg" width="20%"/>

**Comment by hmsjy2017** [comment]
可以用Travis CI 或者 Azure Pipelines，它们有 ARM64 的 runner。

**Comment by XMuli** [comment]
倒是提醒了我，习惯用 GH 自带的， 找到 [arm-action](https://github.com/marketplace/actions/arm-action) 这个，后面我尝试加一下；

**Comment by hmsjy2017** [comment]
希望提供 deb 包，个人觉得二进制不方便管理

**Comment by XMuli** [comment]
已经构建 OK，发现 arm 跑完要 11 min，其它的几个基本 1~3 min。

<img src="https://user-images.githubusercontent.com/33887845/135732080-d3b4c142-02c7-4fa0-b537-9eac4e1ea958.png" width="40%"/>

**Comment by XMuli** [comment]
> 希望提供 deb 包，个人觉得二进制不方便管理

后面再研究下 GitHub 自动构建 package ，看到也有；
