### ISSUE TITLE
已打包 Linux ARM64 deb

### ISSUE THREAD

**Issue by hmsjy2017** [XMuli/ChineseChess#24]
基于最新 commit https://github.com/xmuli/chinessChess/commit/a5798fdfbbebf6f9b307162f3f3771d8cd4f221b 构建，包名为 `chinesechess`。
由于 v5.8.6 之后有较多修改，故版本号改为 v5.8.6+。
尚未测试是否能成功运行，理论上树莓派可以运行，大家可以测试一下。
https://github.com/hmsjy2017/chineseChess-debs/releases/download/v5.6.3%2B/chinesechess_5.8.3+_arm64.deb
稍后会将其添加到 [Raspbian Addons](https://raspbian-addons.org/) 源中。

~~貌似v5.6.3 deb 的 control 是抄 wget 的~~

**Comment by XMuli** [comment]
哇， 感谢

**Comment by XMuli** [comment]
我也后面会研究下怎么自动打包更新，先Mark 下（目前等待时间会略长）；

**Comment by hmsjy2017** [comment]
已加入 Raspbian Addons 源中。
https://apt.raspbian-addons.org/debian/pool/main/c/chinesechess/

**Comment by XMuli** [comment]
看到这个进到 apt 就很开心了，今晚超级开心；有空我也更新一下 README， 和更新一版 Release。

**Comment by hmsjy2017** [comment]
这个 apt 是我参与维护的，弥补了树莓派官方源中软件太少的不足。有兴趣可以了解一下。
https://github.com/raspbian-addons

**Comment by XMuli** [comment]
嗯嗯， 还没有玩过板子，一直都是纯软件

**Comment by XMuli** [comment]
hi~， 我已经更新一个版本到 v6.0， 方便的话大佬可以打包一个  Linux ARM64 deb 的 v6.0 新版本，我随着一起给发出来(2020.01.01 之前即可； 庆祝一下)，我已更新了一些新的功能、关于程序页面中有所有参与贡献者名单；表示对大家感谢，和喜悦的分享

已打包的好的 v6.0 程序有：win、mac、linux(Debian)

**Comment by hmsjy2017** [comment]
存储库名称 chinessChess 是不是拼错了？看着很别扭。应该是 chineseChess 吧。
****
编译速度很快，不到一分钟就完成了
![337A78DC-2738-4EA9-8D6B-8A52288D937E](https://user-images.githubusercontent.com/42692274/147615218-957ed91a-cd7e-4320-88f8-0a67b8a750ff.png)
****
在 chroot 环境下（Debian armhf）编译了 armhf 版本。
![4489F413-4645-4E04-9A3D-2F97966998E9](https://user-images.githubusercontent.com/42692274/147616831-41c90e2c-b219-473c-9ca0-35e3792b5da6.png)

**Comment by hmsjy2017** [comment]
# ChineseChess v6.0 for Linux ARM
## arm64
https://github.com/hmsjy2017/chineseChess-debs/releases/download/v6.0/chinesechess_6.0_arm64.deb
## armhf
增加 armhf 版本。
https://github.com/hmsjy2017/chineseChess-debs/releases/download/v6.0/chinesechess_6.0_armhf.deb

**Comment by XMuli** [comment]
> 存储库名称 chinessChess 是不是拼错了？看着很别扭。应该是 chineseChess 吧。

 是，~~暂先这样（吧），无奈~~

蟹蟹打包， 辛苦； 发布 release 筹划中

**Comment by hmsjy2017** [comment]
可以考虑增加 Linux i386 、 Windows x86/arm64 和 macOS arm64版本，这样基本支持全平台全架构了，~~要不顺便支持一下 Linux mips64、Linux ppc64、FreeBSD~~。
可以写个脚本，每当创建新 tag 时自动编译打包并上传 release。

**Comment by XMuli** [comment]
> 可以考虑增加 Linux i386 、 Windows x86/arm64 和 macOS arm64版本，这样基本支持全平台全架构了，要不顺便支持一下 Linux mips64、Linux ppc64、FreeBSD。

代码层次这些理论都是支持的。暂无对应实体设备，云设备尝试过 gh 的action，后面还会再去写一下 对应 gh action 的 .yml 脚本，自动编译且打包上传

~~(前面尝试写的时候，一直是 fail；目前也在忙着开新坑在)~~

**Comment by hmsjy2017** [comment]
对于 arm64 架构可以使用自托管的运行器（[self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)）来构建，这样编译速度可能会快一些。arm64 VPS 可以向 [Fosshost](https://fosshost.org/) 免费申请 。

**Comment by XMuli** [comment]
昂~；想 Mark 下； 目前最新版本都已经更到 [https://github.com/xmuli/chinessChess/releases/tag/v6.0](https://github.com/xmuli/chinessChess/releases/tag/v6.0)； 

结帖； 顺便，**新年快乐鸭~~** ✨✨

**Comment by hmsjy2017** [comment]
~~为什么把 v5.8.3 的 deb 也发了进去...~~

**Comment by XMuli** [comment]
v5.8.3 已移除
