### ISSUE TITLE
使用包管理器安装 ChineseChess

### ISSUE THREAD

**Issue by hmsjy2017** [XMuli/ChineseChess#28]
**目前此方法仅支持 Debian/Ubuntu 的 arm/arm64 架构。**
1. 首先安装脚本所需的依赖 `curl` 和 `python3`。
```shell
sudo apt install -y curl python3
```

2. 添加 [Raspbian Addons](https://raspbian-addons.org/) apt 存储库。
```shell
python3 <(curl -fSsL https://cdn.jsdelivr.net/gh/raspbian-addons/scripts@master/utils/repo.py)
```
根据提示选择一个离你最近的镜像站。

3. 安装 ChineseChess
```shell
sudo apt install chinesechess
```

****
如果需要卸载，请执行以下命令：
```shell
sudo apt remove chinesechess
```

**Comment by XMuli** [comment]
早上好，起来挺早的鸭~；


我把这个更新到 WiKi 中 （已加入 [chinessChess/wiki）](https://github.com/xmuli/chinessChess/wiki)
