### ISSUE TITLE
Please add support for Pikafish so that we can analyze moves.

### ISSUE THREAD

**Issue by ntos1978** [XMuli/ChineseChess#39]

**Comment by ntos1978** [comment]
Please add this feature especially for linux as there are already many Xiangqi apps with this feature in Windows. Thank you very much.

**Comment by XMuli** [comment]
If you want to integrate it，Please fork and modify the source code. If it is a promotion, please stop this behavior.

**Comment by ntos1978** [comment]
My coding skill is not good enough to integrate Pikafish. And I am not promoting anything as PIkafish is open source. If you could please suggest how to code the integration in the readme file, I would be glad to try it.

**Comment by XMuli** [comment]
ok, my friend.But I have no plans to integrate this engine for the time being, maybe in the future.
