### ISSUE TITLE
接受外部PR吗

### ISSUE THREAD

**Issue by BlueArvin** [XMuli/ChineseChess#4]
发现项目里有些影响使用体验的小bug  自己练习的时候顺便改了一些 考虑开个分支接受其他人的pull request吗

**Comment by XMuli** [comment]
非常欢迎，READ.md 明确写的很清楚，欢迎贡献，注意提交规范保持一致即可

**Comment by BlueArvin** [comment]
直接提master吗 还是开一个单独的pr分支吧 之后如果验证没问题 你再往master合

**Comment by XMuli** [comment]
都行， 最后推送到我的 master 即可; 可以参考已经提交的 [pr 已合](https://github.com/xmuli/chinessChess/pulls?q=is%3Apr+is%3Aclosed)

**Comment by XMuli** [comment]
建议自己新建分支，这样的话，更加规范～

**Comment by BlueArvin** [comment]
我意思是你开一个单独的pr分支推上来( eg: dev_pr )  外部的pr往这个分支上提  你在这个分支上验证了之后再往你的master分支上合

**Comment by XMuli** [comment]
现阶段这个体量还达不到，从简，直接合并 master
